### PR TITLE
Fix broken links in README

### PR DESCRIPTION
**Pull request by ymorimo**
Fixes the URLs of the sub-docs linked from README files.

### CODE REVIEW

**Comment by tei-k** [comment]
Maybe already fixed in #23

**Comment by ymorimo** [comment]
> Maybe already fixed in #23

Oh... sorry, I forgot to pull the latest `main`.
But I found a broken link in `aws/README.md` (A leading unnecessary dot was in the link), and `tree` instead of `blob` seems to be a normalized link when it points to a directory.

**Review by tei-k — APPROVED** [review]
LGTM!

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Pull request merged**
