### PR TITLE
Output inventory ini

### PR DESCRIPTION
**Pull request by tei-k**
# Description
Need to merge https://github.com/scalar-labs/scalar-terraform/pull/281 first.

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Comment by feeblefakie** [comment]
@tei-k CI fails because the `scalar-terraform` PR is not merged yet?

**Comment by tei-k** [comment]
>CI fails because the scalar-terraform PR is not merged yet?

Yes, Need to merge this PR https://github.com/scalar-labs/scalar-terraform/pull/281

```
Error: Reference to undeclared output value

  on output.tf line 2, in output "inventory_ini":
   2:   value = module.ca.inventory_ini

An output value with the name "inventory_ini" has not been declared in
module.ca.
```

**Comment by feeblefakie** [comment]
@tei-k Rerun CI but it seems still failing even scalar-labs/scalar-terraform#281 is merged.

**Comment by tei-k** [comment]
>Rerun CI but it seems still failing even scalar-labs/scalar-terraform#281 is merged.

@feeblefakie We need to rerun all ci per module. All successful now.

**Pull request merged**
